### ISSUE TITLE
Error when piping to jq

### ISSUE THREAD

**Issue by jsgv** [tidwall/pretty#14]
I get an error when using `pretty.Color` and then trying to pipe that to [jq](https://stedolan.github.io/jq/). It prints correctly as desired, but does not work with jq.

```go
// v = interface{}

b, _ := json.Marshal(v)
d := string(pretty.Color(b, nil))

fmt.Fprintln(
	os.Stdout,
	d,
)

```

Pipe the results of the command to jq:

`thecommand | jq`

```
parse error: Invalid numeric literal at line 1, column 3
```

Using `pretty.Pretty(b)` works, but it does not have the desired colorized output.

**Comment by tidwall** [comment]
The problem is that `pretty.PrettyColor` injects a bunch of bytes into the JSON making it invalid for parsing. Those bytes make it pretty for display, but when JQ receives the json from the pipe, it chokes.

The trick is check if the process is a tty terminal and not a pipe.

```go
package main

import (
	"fmt"
	"os"

        "github.com/tidwall/pretty"
	"golang.org/x/crypto/ssh/terminal"
)

func prettyColorForPiping(json []byte) []byte {
	if terminal.IsTerminal(int(os.Stdin.Fd())) {
		return pretty.Color(json, nil)
	}
	return pretty.Pretty(json)
}

func main() {
	// b, _ := json.Marshal(v)
	b := []byte(`{"hello":"world"}`)
	d := string(prettyColorForPiping(b))

	fmt.Fprintln(
		os.Stdout,
		d,
	)
}

```


The pretty.PrettyColor should only be used with a tty terminal.

**Comment by jsgv** [comment]
Thanks for the reply. I appreciate it.

I did realize what the problem was after I created the issue.
